name       : python-pyheif
version    : 0.7.1
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/p/pyheif/pyheif-0.7.1.tar.gz : 86a5c5174379d7146b5ed1a68892faf7268a135fb7f5039a011bfb7a6e903200
homepage   : https://github.com/carsales/pyheif
license    : Apache-2.0
component  : programming.python
summary    : Python 3.6+ interface to libheif library
description: |
    Python 3.6+ interface to libheif library
builddeps  :
    - pkgconfig(libheif)
    - pkgconfig(python3)
    - python-cffi
rundeps    :
    - python-cffi
build      : |
    %python3_setup
install    : |
    %python3_install
